[package]
name = "tigers-eye-mvp"
version = "0.1.0"
authors = ["Daniel Fitchmun <daniel@somatek.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
